// This file is auto-generated by @hey-api/openapi-ts

import type { FormKitSchemaNode } from '@formkit/core'

export const CategoryFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'required|length:0,100',
  },
  {
    $formkit: 'text',
    name: 'slug',
    label: 'Slug',
    validation: 'required|length:0,100',
  },
]

export const OrderFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'text',
    name: 'customer_name',
    label: 'Customer name',
    validation: 'required|length:0,200',
  },
  {
    $formkit: 'select',
    name: 'status',
    label: 'Status',
    options: [
      {
        value: 'pending',
        label: 'Pending',
      },
      {
        value: 'paid',
        label: 'Paid',
      },
      {
        value: 'shipped',
        label: 'Shipped',
      },
      {
        value: 'cancelled',
        label: 'Cancelled',
      },
    ],
  },
  {
    $formkit: 'repeater',
    name: 'items',
    children: [
      {
        $formkit: 'number',
        name: 'product',
        label: 'Product',
        validation: 'required',
      },
      {
        $formkit: 'number',
        name: 'quantity',
        label: 'Quantity',
        validation: 'min:0|max:2147483647',
      },
      {
        $formkit: 'text',
        name: 'unit_price',
        label: 'Unit price',
        validation: 'required|number',
      },
    ],
  },
]

export const OrderItemFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'number',
    name: 'product',
    label: 'Product',
    validation: 'required',
  },
  {
    $formkit: 'number',
    name: 'quantity',
    label: 'Quantity',
    validation: 'min:0|max:2147483647',
  },
  {
    $formkit: 'text',
    name: 'unit_price',
    label: 'Unit price',
    validation: 'required|number',
  },
]

export const PatchedCategoryFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'length:0,100',
  },
  {
    $formkit: 'text',
    name: 'slug',
    label: 'Slug',
    validation: 'length:0,100',
  },
]

export const PatchedOrderFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'text',
    name: 'customer_name',
    label: 'Customer name',
    validation: 'length:0,200',
  },
  {
    $formkit: 'select',
    name: 'status',
    label: 'Status',
    options: [
      {
        value: 'pending',
        label: 'Pending',
      },
      {
        value: 'paid',
        label: 'Paid',
      },
      {
        value: 'shipped',
        label: 'Shipped',
      },
      {
        value: 'cancelled',
        label: 'Cancelled',
      },
    ],
  },
  {
    $formkit: 'repeater',
    name: 'items',
    children: [
      {
        $formkit: 'number',
        name: 'product',
        label: 'Product',
        validation: 'required',
      },
      {
        $formkit: 'number',
        name: 'quantity',
        label: 'Quantity',
        validation: 'min:0|max:2147483647',
      },
      {
        $formkit: 'text',
        name: 'unit_price',
        label: 'Unit price',
        validation: 'required|number',
      },
    ],
  },
]

export const PatchedProductFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'length:0,200',
  },
  {
    $formkit: 'text',
    name: 'description',
    label: 'Description',
  },
  {
    $formkit: 'text',
    name: 'price',
    label: 'Price',
    validation: 'number',
  },
  {
    $formkit: 'checkbox',
    name: 'in_stock',
    label: 'In stock',
  },
  {
    $formkit: 'number',
    name: 'category',
    label: 'Category',
  },
  {
    $formkit: 'number',
    name: 'supplier',
    label: 'Supplier',
  },
]

export const PatchedSupplierFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'length:0,200',
  },
  {
    $formkit: 'email',
    name: 'email',
    label: 'Email',
    validation: 'email|length:0,254',
  },
]

export const ProductFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'required|length:0,200',
  },
  {
    $formkit: 'text',
    name: 'description',
    label: 'Description',
  },
  {
    $formkit: 'text',
    name: 'price',
    label: 'Price',
    validation: 'required|number',
  },
  {
    $formkit: 'checkbox',
    name: 'in_stock',
    label: 'In stock',
  },
  {
    $formkit: 'number',
    name: 'category',
    label: 'Category',
  },
  {
    $formkit: 'number',
    name: 'supplier',
    label: 'Supplier',
    validation: 'required',
  },
]

export const SupplierFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'required|length:0,200',
  },
  {
    $formkit: 'email',
    name: 'email',
    label: 'Email',
    validation: 'email|length:0,254',
  },
]

export const CategoryWritableFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'required|length:0,100',
  },
  {
    $formkit: 'text',
    name: 'slug',
    label: 'Slug',
    validation: 'required|length:0,100',
  },
]

export const OrderWritableFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'text',
    name: 'customer_name',
    label: 'Customer name',
    validation: 'required|length:0,200',
  },
  {
    $formkit: 'select',
    name: 'status',
    label: 'Status',
    options: [
      {
        value: 'pending',
        label: 'Pending',
      },
      {
        value: 'paid',
        label: 'Paid',
      },
      {
        value: 'shipped',
        label: 'Shipped',
      },
      {
        value: 'cancelled',
        label: 'Cancelled',
      },
    ],
  },
  {
    $formkit: 'repeater',
    name: 'items',
    children: [
      {
        $formkit: 'number',
        name: 'product',
        label: 'Product',
        validation: 'required',
      },
      {
        $formkit: 'number',
        name: 'quantity',
        label: 'Quantity',
        validation: 'min:0|max:2147483647',
      },
      {
        $formkit: 'text',
        name: 'unit_price',
        label: 'Unit price',
        validation: 'required|number',
      },
    ],
  },
]

export const OrderItemWritableFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'number',
    name: 'product',
    label: 'Product',
    validation: 'required',
  },
  {
    $formkit: 'number',
    name: 'quantity',
    label: 'Quantity',
    validation: 'min:0|max:2147483647',
  },
  {
    $formkit: 'text',
    name: 'unit_price',
    label: 'Unit price',
    validation: 'required|number',
  },
]

export const PatchedCategoryWritableFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'length:0,100',
  },
  {
    $formkit: 'text',
    name: 'slug',
    label: 'Slug',
    validation: 'length:0,100',
  },
]

export const PatchedOrderWritableFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'text',
    name: 'customer_name',
    label: 'Customer name',
    validation: 'length:0,200',
  },
  {
    $formkit: 'select',
    name: 'status',
    label: 'Status',
    options: [
      {
        value: 'pending',
        label: 'Pending',
      },
      {
        value: 'paid',
        label: 'Paid',
      },
      {
        value: 'shipped',
        label: 'Shipped',
      },
      {
        value: 'cancelled',
        label: 'Cancelled',
      },
    ],
  },
  {
    $formkit: 'repeater',
    name: 'items',
    children: [
      {
        $formkit: 'number',
        name: 'product',
        label: 'Product',
        validation: 'required',
      },
      {
        $formkit: 'number',
        name: 'quantity',
        label: 'Quantity',
        validation: 'min:0|max:2147483647',
      },
      {
        $formkit: 'text',
        name: 'unit_price',
        label: 'Unit price',
        validation: 'required|number',
      },
    ],
  },
]

export const PatchedProductWritableFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'length:0,200',
  },
  {
    $formkit: 'text',
    name: 'description',
    label: 'Description',
  },
  {
    $formkit: 'text',
    name: 'price',
    label: 'Price',
    validation: 'number',
  },
  {
    $formkit: 'checkbox',
    name: 'in_stock',
    label: 'In stock',
  },
  {
    $formkit: 'number',
    name: 'category',
    label: 'Category',
  },
  {
    $formkit: 'number',
    name: 'supplier',
    label: 'Supplier',
  },
]

export const PatchedSupplierWritableFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'length:0,200',
  },
  {
    $formkit: 'email',
    name: 'email',
    label: 'Email',
    validation: 'email|length:0,254',
  },
]

export const ProductWritableFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'required|length:0,200',
  },
  {
    $formkit: 'text',
    name: 'description',
    label: 'Description',
  },
  {
    $formkit: 'text',
    name: 'price',
    label: 'Price',
    validation: 'required|number',
  },
  {
    $formkit: 'checkbox',
    name: 'in_stock',
    label: 'In stock',
  },
  {
    $formkit: 'number',
    name: 'category',
    label: 'Category',
  },
  {
    $formkit: 'number',
    name: 'supplier',
    label: 'Supplier',
    validation: 'required',
  },
]

export const SupplierWritableFormKitSchema: Array<FormKitSchemaNode> = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'required|length:0,200',
  },
  {
    $formkit: 'email',
    name: 'email',
    label: 'Email',
    validation: 'email|length:0,254',
  },
]
