// This file is auto-generated by @hey-api/openapi-ts

export const CategorySchema = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      readOnly: true,
    },
    name: {
      type: 'string',
      maxLength: 100,
    },
    slug: {
      type: 'string',
      maxLength: 100,
      pattern: '^[-a-zA-Z0-9_]+$',
    },
  },
  required: ['id', 'name', 'slug'],
} as const

export const OrderSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      readOnly: true,
    },
    customer_name: {
      type: 'string',
      maxLength: 200,
    },
    status: {
      $ref: '#/components/schemas/StatusEnum',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      readOnly: true,
    },
    items: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/OrderItem',
      },
    },
  },
  required: ['created_at', 'customer_name', 'id', 'items'],
} as const

export const OrderItemSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      readOnly: true,
    },
    product: {
      type: 'integer',
    },
    product_name: {
      type: 'string',
      readOnly: true,
    },
    quantity: {
      type: 'integer',
      maximum: 2147483647,
      minimum: 0,
    },
    unit_price: {
      type: 'string',
      format: 'decimal',
      pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
    },
  },
  required: ['id', 'product', 'product_name', 'unit_price'],
} as const

export const PatchedCategorySchema = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      readOnly: true,
    },
    name: {
      type: 'string',
      maxLength: 100,
    },
    slug: {
      type: 'string',
      maxLength: 100,
      pattern: '^[-a-zA-Z0-9_]+$',
    },
  },
} as const

export const PatchedOrderSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      readOnly: true,
    },
    customer_name: {
      type: 'string',
      maxLength: 200,
    },
    status: {
      $ref: '#/components/schemas/StatusEnum',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      readOnly: true,
    },
    items: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/OrderItem',
      },
    },
  },
} as const

export const PatchedProductSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      readOnly: true,
    },
    name: {
      type: 'string',
      maxLength: 200,
    },
    description: {
      type: 'string',
    },
    price: {
      type: 'string',
      format: 'decimal',
      pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
    },
    in_stock: {
      type: 'boolean',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      readOnly: true,
    },
    category: {
      type: 'integer',
      nullable: true,
    },
    category_name: {
      type: 'string',
      readOnly: true,
    },
    supplier: {
      type: 'integer',
    },
    supplier_name: {
      type: 'string',
      readOnly: true,
    },
  },
} as const

export const PatchedSupplierSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      readOnly: true,
    },
    name: {
      type: 'string',
      maxLength: 200,
    },
    email: {
      type: 'string',
      format: 'email',
      maxLength: 254,
    },
  },
} as const

export const ProductSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      readOnly: true,
    },
    name: {
      type: 'string',
      maxLength: 200,
    },
    description: {
      type: 'string',
    },
    price: {
      type: 'string',
      format: 'decimal',
      pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
    },
    in_stock: {
      type: 'boolean',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      readOnly: true,
    },
    category: {
      type: 'integer',
      nullable: true,
    },
    category_name: {
      type: 'string',
      readOnly: true,
    },
    supplier: {
      type: 'integer',
    },
    supplier_name: {
      type: 'string',
      readOnly: true,
    },
  },
  required: ['category_name', 'created_at', 'id', 'name', 'price', 'supplier', 'supplier_name'],
} as const

export const StatusEnumSchema = {
  enum: ['pending', 'paid', 'shipped', 'cancelled'],
  type: 'string',
  description:
    '* `pending` - Pending\n* `paid` - Paid\n* `shipped` - Shipped\n* `cancelled` - Cancelled',
} as const

export const SupplierSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      readOnly: true,
    },
    name: {
      type: 'string',
      maxLength: 200,
    },
    email: {
      type: 'string',
      format: 'email',
      maxLength: 254,
    },
  },
  required: ['id', 'name'],
} as const

export const CategoryWritableSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
      maxLength: 100,
    },
    slug: {
      type: 'string',
      maxLength: 100,
      pattern: '^[-a-zA-Z0-9_]+$',
    },
  },
  required: ['name', 'slug'],
} as const

export const OrderWritableSchema = {
  type: 'object',
  properties: {
    customer_name: {
      type: 'string',
      maxLength: 200,
    },
    status: {
      $ref: '#/components/schemas/StatusEnum',
    },
    items: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/OrderItemWritable',
      },
    },
  },
  required: ['customer_name', 'items'],
} as const

export const OrderItemWritableSchema = {
  type: 'object',
  properties: {
    product: {
      type: 'integer',
    },
    quantity: {
      type: 'integer',
      maximum: 2147483647,
      minimum: 0,
    },
    unit_price: {
      type: 'string',
      format: 'decimal',
      pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
    },
  },
  required: ['product', 'unit_price'],
} as const

export const PatchedCategoryWritableSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
      maxLength: 100,
    },
    slug: {
      type: 'string',
      maxLength: 100,
      pattern: '^[-a-zA-Z0-9_]+$',
    },
  },
} as const

export const PatchedOrderWritableSchema = {
  type: 'object',
  properties: {
    customer_name: {
      type: 'string',
      maxLength: 200,
    },
    status: {
      $ref: '#/components/schemas/StatusEnum',
    },
    items: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/OrderItemWritable',
      },
    },
  },
} as const

export const PatchedProductWritableSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
      maxLength: 200,
    },
    description: {
      type: 'string',
    },
    price: {
      type: 'string',
      format: 'decimal',
      pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
    },
    in_stock: {
      type: 'boolean',
    },
    category: {
      type: 'integer',
      nullable: true,
    },
    supplier: {
      type: 'integer',
    },
  },
} as const

export const PatchedSupplierWritableSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
      maxLength: 200,
    },
    email: {
      type: 'string',
      format: 'email',
      maxLength: 254,
    },
  },
} as const

export const ProductWritableSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
      maxLength: 200,
    },
    description: {
      type: 'string',
    },
    price: {
      type: 'string',
      format: 'decimal',
      pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
    },
    in_stock: {
      type: 'boolean',
    },
    category: {
      type: 'integer',
      nullable: true,
    },
    supplier: {
      type: 'integer',
    },
  },
  required: ['name', 'price', 'supplier'],
} as const

export const SupplierWritableSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
      maxLength: 200,
    },
    email: {
      type: 'string',
      format: 'email',
      maxLength: 254,
    },
  },
  required: ['name'],
} as const
