// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

export type Category = {
  readonly id: number
  name: string
  slug: string
}

/**
 * Request body for the login endpoint.
 */
export type Login = {
  username: string
  password: string
}

export type Order = {
  readonly id: number
  customer_name: string
  status?: StatusEnum
  readonly created_at: string
  items: Array<OrderItem>
}

export type OrderItem = {
  pk?: number
  product: number
  readonly product_name: string
  quantity?: number
  unit_price: string
}

export type PatchedCategory = {
  readonly id?: number
  name?: string
  slug?: string
}

export type PatchedOrder = {
  readonly id?: number
  customer_name?: string
  status?: StatusEnum
  readonly created_at?: string
  items?: Array<OrderItem>
}

export type PatchedProduct = {
  readonly id?: number
  name?: string
  description?: string
  price?: string
  in_stock?: boolean
  readonly created_at?: string
  category?: number | null
  readonly category_name?: string
  supplier?: number
  readonly supplier_name?: string
}

export type PatchedSupplier = {
  readonly id?: number
  name?: string
  email?: string
}

export type Product = {
  readonly id: number
  name: string
  description?: string
  price: string
  in_stock?: boolean
  readonly created_at: string
  category?: number | null
  readonly category_name: string
  supplier: number
  readonly supplier_name: string
}

/**
 * * `pending` - Pending
 * * `paid` - Paid
 * * `shipped` - Shipped
 * * `cancelled` - Cancelled
 */
export const StatusEnum = {
  PENDING: 'pending',
  PAID: 'paid',
  SHIPPED: 'shipped',
  CANCELLED: 'cancelled',
} as const

/**
 * * `pending` - Pending
 * * `paid` - Paid
 * * `shipped` - Shipped
 * * `cancelled` - Cancelled
 */
export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum]

export type Supplier = {
  readonly id: number
  name: string
  email?: string
}

/**
 * Login response: the auth token to send as ``Authorization: Bearer``.
 */
export type Token = {
  readonly token: string
}

export type CategoryWritable = {
  name: string
  slug: string
}

export type OrderWritable = {
  customer_name: string
  status?: StatusEnum
  items: Array<OrderItemWritable>
}

export type OrderItemWritable = {
  pk?: number
  product: number
  quantity?: number
  unit_price: string
}

export type PatchedCategoryWritable = {
  name?: string
  slug?: string
}

export type PatchedOrderWritable = {
  customer_name?: string
  status?: StatusEnum
  items?: Array<OrderItemWritable>
}

export type PatchedProductWritable = {
  name?: string
  description?: string
  price?: string
  in_stock?: boolean
  category?: number | null
  supplier?: number
}

export type PatchedSupplierWritable = {
  name?: string
  email?: string
}

export type ProductWritable = {
  name: string
  description?: string
  price: string
  in_stock?: boolean
  category?: number | null
  supplier: number
}

export type SupplierWritable = {
  name: string
  email?: string
}

export type LoginData = {
  body: Login
  path?: never
  query?: never
  url: '/api/auth/login/'
}

export type LoginResponses = {
  200: Token
}

export type LoginResponse = LoginResponses[keyof LoginResponses]

export type CategoriesListData = {
  body?: never
  path?: never
  query?: never
  url: '/api/categories/'
}

export type CategoriesListResponses = {
  200: Array<Category>
}

export type CategoriesListResponse = CategoriesListResponses[keyof CategoriesListResponses]

export type CategoriesCreateData = {
  body: CategoryWritable
  path?: never
  query?: never
  url: '/api/categories/'
}

export type CategoriesCreateResponses = {
  201: Category
}

export type CategoriesCreateResponse = CategoriesCreateResponses[keyof CategoriesCreateResponses]

export type CategoriesDestroyData = {
  body?: never
  path: {
    /**
     * A unique integer value identifying this category.
     */
    id: number
  }
  query?: never
  url: '/api/categories/{id}/'
}

export type CategoriesDestroyResponses = {
  /**
   * No response body
   */
  204: void
}

export type CategoriesDestroyResponse = CategoriesDestroyResponses[keyof CategoriesDestroyResponses]

export type CategoriesRetrieveData = {
  body?: never
  path: {
    /**
     * A unique integer value identifying this category.
     */
    id: number
  }
  query?: never
  url: '/api/categories/{id}/'
}

export type CategoriesRetrieveResponses = {
  200: Category
}

export type CategoriesRetrieveResponse =
  CategoriesRetrieveResponses[keyof CategoriesRetrieveResponses]

export type CategoriesPartialUpdateData = {
  body?: PatchedCategoryWritable
  path: {
    /**
     * A unique integer value identifying this category.
     */
    id: number
  }
  query?: never
  url: '/api/categories/{id}/'
}

export type CategoriesPartialUpdateResponses = {
  200: Category
}

export type CategoriesPartialUpdateResponse =
  CategoriesPartialUpdateResponses[keyof CategoriesPartialUpdateResponses]

export type CategoriesUpdateData = {
  body: CategoryWritable
  path: {
    /**
     * A unique integer value identifying this category.
     */
    id: number
  }
  query?: never
  url: '/api/categories/{id}/'
}

export type CategoriesUpdateResponses = {
  200: Category
}

export type CategoriesUpdateResponse = CategoriesUpdateResponses[keyof CategoriesUpdateResponses]

export type OrdersListData = {
  body?: never
  path?: never
  query?: never
  url: '/api/orders/'
}

export type OrdersListResponses = {
  200: Array<Order>
}

export type OrdersListResponse = OrdersListResponses[keyof OrdersListResponses]

export type OrdersCreateData = {
  body: OrderWritable
  path?: never
  query?: never
  url: '/api/orders/'
}

export type OrdersCreateResponses = {
  201: Order
}

export type OrdersCreateResponse = OrdersCreateResponses[keyof OrdersCreateResponses]

export type OrdersDestroyData = {
  body?: never
  path: {
    /**
     * A unique integer value identifying this order.
     */
    id: number
  }
  query?: never
  url: '/api/orders/{id}/'
}

export type OrdersDestroyResponses = {
  /**
   * No response body
   */
  204: void
}

export type OrdersDestroyResponse = OrdersDestroyResponses[keyof OrdersDestroyResponses]

export type OrdersRetrieveData = {
  body?: never
  path: {
    /**
     * A unique integer value identifying this order.
     */
    id: number
  }
  query?: never
  url: '/api/orders/{id}/'
}

export type OrdersRetrieveResponses = {
  200: Order
}

export type OrdersRetrieveResponse = OrdersRetrieveResponses[keyof OrdersRetrieveResponses]

export type OrdersPartialUpdateData = {
  body?: PatchedOrderWritable
  path: {
    /**
     * A unique integer value identifying this order.
     */
    id: number
  }
  query?: never
  url: '/api/orders/{id}/'
}

export type OrdersPartialUpdateResponses = {
  200: Order
}

export type OrdersPartialUpdateResponse =
  OrdersPartialUpdateResponses[keyof OrdersPartialUpdateResponses]

export type OrdersUpdateData = {
  body: OrderWritable
  path: {
    /**
     * A unique integer value identifying this order.
     */
    id: number
  }
  query?: never
  url: '/api/orders/{id}/'
}

export type OrdersUpdateResponses = {
  200: Order
}

export type OrdersUpdateResponse = OrdersUpdateResponses[keyof OrdersUpdateResponses]

export type ProductsListData = {
  body?: never
  path?: never
  query?: never
  url: '/api/products/'
}

export type ProductsListResponses = {
  200: Array<Product>
}

export type ProductsListResponse = ProductsListResponses[keyof ProductsListResponses]

export type ProductsCreateData = {
  body: ProductWritable
  path?: never
  query?: never
  url: '/api/products/'
}

export type ProductsCreateResponses = {
  201: Product
}

export type ProductsCreateResponse = ProductsCreateResponses[keyof ProductsCreateResponses]

export type ProductsDestroyData = {
  body?: never
  path: {
    /**
     * A unique integer value identifying this product.
     */
    id: number
  }
  query?: never
  url: '/api/products/{id}/'
}

export type ProductsDestroyResponses = {
  /**
   * No response body
   */
  204: void
}

export type ProductsDestroyResponse = ProductsDestroyResponses[keyof ProductsDestroyResponses]

export type ProductsRetrieveData = {
  body?: never
  path: {
    /**
     * A unique integer value identifying this product.
     */
    id: number
  }
  query?: never
  url: '/api/products/{id}/'
}

export type ProductsRetrieveResponses = {
  200: Product
}

export type ProductsRetrieveResponse = ProductsRetrieveResponses[keyof ProductsRetrieveResponses]

export type ProductsPartialUpdateData = {
  body?: PatchedProductWritable
  path: {
    /**
     * A unique integer value identifying this product.
     */
    id: number
  }
  query?: never
  url: '/api/products/{id}/'
}

export type ProductsPartialUpdateResponses = {
  200: Product
}

export type ProductsPartialUpdateResponse =
  ProductsPartialUpdateResponses[keyof ProductsPartialUpdateResponses]

export type ProductsUpdateData = {
  body: ProductWritable
  path: {
    /**
     * A unique integer value identifying this product.
     */
    id: number
  }
  query?: never
  url: '/api/products/{id}/'
}

export type ProductsUpdateResponses = {
  200: Product
}

export type ProductsUpdateResponse = ProductsUpdateResponses[keyof ProductsUpdateResponses]

export type SuppliersListData = {
  body?: never
  path?: never
  query?: never
  url: '/api/suppliers/'
}

export type SuppliersListResponses = {
  200: Array<Supplier>
}

export type SuppliersListResponse = SuppliersListResponses[keyof SuppliersListResponses]

export type SuppliersCreateData = {
  body: SupplierWritable
  path?: never
  query?: never
  url: '/api/suppliers/'
}

export type SuppliersCreateResponses = {
  201: Supplier
}

export type SuppliersCreateResponse = SuppliersCreateResponses[keyof SuppliersCreateResponses]

export type SuppliersDestroyData = {
  body?: never
  path: {
    /**
     * A unique integer value identifying this supplier.
     */
    id: number
  }
  query?: never
  url: '/api/suppliers/{id}/'
}

export type SuppliersDestroyResponses = {
  /**
   * No response body
   */
  204: void
}

export type SuppliersDestroyResponse = SuppliersDestroyResponses[keyof SuppliersDestroyResponses]

export type SuppliersRetrieveData = {
  body?: never
  path: {
    /**
     * A unique integer value identifying this supplier.
     */
    id: number
  }
  query?: never
  url: '/api/suppliers/{id}/'
}

export type SuppliersRetrieveResponses = {
  200: Supplier
}

export type SuppliersRetrieveResponse = SuppliersRetrieveResponses[keyof SuppliersRetrieveResponses]

export type SuppliersPartialUpdateData = {
  body?: PatchedSupplierWritable
  path: {
    /**
     * A unique integer value identifying this supplier.
     */
    id: number
  }
  query?: never
  url: '/api/suppliers/{id}/'
}

export type SuppliersPartialUpdateResponses = {
  200: Supplier
}

export type SuppliersPartialUpdateResponse =
  SuppliersPartialUpdateResponses[keyof SuppliersPartialUpdateResponses]

export type SuppliersUpdateData = {
  body: SupplierWritable
  path: {
    /**
     * A unique integer value identifying this supplier.
     */
    id: number
  }
  query?: never
  url: '/api/suppliers/{id}/'
}

export type SuppliersUpdateResponses = {
  200: Supplier
}

export type SuppliersUpdateResponse = SuppliersUpdateResponses[keyof SuppliersUpdateResponses]
