// This file is auto-generated by @hey-api/openapi-ts

export const CategoryFormKitSchema = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'required|length:0,100',
  },
  {
    $formkit: 'text',
    name: 'slug',
    label: 'Slug',
    validation: 'required|length:0,100',
  },
]

export const OrderFormKitSchema = [
  {
    $formkit: 'text',
    name: 'customer_name',
    label: 'Customer name',
    validation: 'required|length:0,200',
  },
  {
    $formkit: 'select',
    name: 'status',
    label: 'Status',
    options: [
      {
        value: 'pending',
        label: 'Pending',
      },
      {
        value: 'paid',
        label: 'Paid',
      },
      {
        value: 'shipped',
        label: 'Shipped',
      },
      {
        value: 'cancelled',
        label: 'Cancelled',
      },
    ],
  },
  {
    $formkit: 'list',
    name: 'items',
    children: [
      {
        $formkit: 'group',
        for: ['row', 'index', '$items_rows'],
        key: '$row.key',
        children: [
          {
            $formkit: 'select',
            name: 'product',
            label: 'Product',
            options: '$productOptions',
            placeholder: 'Select a product…',
            validation: 'required',
          },
          {
            $formkit: 'number',
            name: 'quantity',
            label: 'Quantity',
            validation: 'min:0|max:2147483647',
          },
          {
            $formkit: 'text',
            name: 'unit_price',
            label: 'Unit price',
            validation: 'required|number',
          },
          {
            $el: 'button',
            attrs: {
              type: 'button',
              class: 'formkit-remove',
              onClick: '$items_remove($index)',
            },
            children: 'Remove',
          },
        ],
      },
    ],
  },
]

export const OrderItemFormKitSchema = [
  {
    $formkit: 'select',
    name: 'product',
    label: 'Product',
    options: '$productOptions',
    placeholder: 'Select a product…',
    validation: 'required',
  },
  {
    $formkit: 'number',
    name: 'quantity',
    label: 'Quantity',
    validation: 'min:0|max:2147483647',
  },
  {
    $formkit: 'text',
    name: 'unit_price',
    label: 'Unit price',
    validation: 'required|number',
  },
]

export const PatchedCategoryFormKitSchema = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'length:0,100',
  },
  {
    $formkit: 'text',
    name: 'slug',
    label: 'Slug',
    validation: 'length:0,100',
  },
]

export const PatchedOrderFormKitSchema = [
  {
    $formkit: 'text',
    name: 'customer_name',
    label: 'Customer name',
    validation: 'length:0,200',
  },
  {
    $formkit: 'select',
    name: 'status',
    label: 'Status',
    options: [
      {
        value: 'pending',
        label: 'Pending',
      },
      {
        value: 'paid',
        label: 'Paid',
      },
      {
        value: 'shipped',
        label: 'Shipped',
      },
      {
        value: 'cancelled',
        label: 'Cancelled',
      },
    ],
  },
  {
    $formkit: 'list',
    name: 'items',
    children: [
      {
        $formkit: 'group',
        for: ['row', 'index', '$items_rows'],
        key: '$row.key',
        children: [
          {
            $formkit: 'select',
            name: 'product',
            label: 'Product',
            options: '$productOptions',
            placeholder: 'Select a product…',
            validation: 'required',
          },
          {
            $formkit: 'number',
            name: 'quantity',
            label: 'Quantity',
            validation: 'min:0|max:2147483647',
          },
          {
            $formkit: 'text',
            name: 'unit_price',
            label: 'Unit price',
            validation: 'required|number',
          },
          {
            $el: 'button',
            attrs: {
              type: 'button',
              class: 'formkit-remove',
              onClick: '$items_remove($index)',
            },
            children: 'Remove',
          },
        ],
      },
    ],
  },
]

export const PatchedProductFormKitSchema = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'length:0,200',
  },
  {
    $formkit: 'text',
    name: 'description',
    label: 'Description',
  },
  {
    $formkit: 'text',
    name: 'price',
    label: 'Price',
    validation: 'number',
  },
  {
    $formkit: 'checkbox',
    name: 'in_stock',
    label: 'In stock',
  },
  {
    $formkit: 'select',
    name: 'category',
    label: 'Category',
    options: '$categoryOptions',
  },
  {
    $formkit: 'select',
    name: 'supplier',
    label: 'Supplier',
    options: '$supplierOptions',
  },
]

export const PatchedSupplierFormKitSchema = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'length:0,200',
  },
  {
    $formkit: 'email',
    name: 'email',
    label: 'Email',
    validation: 'email|length:0,254',
  },
]

export const ProductFormKitSchema = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'required|length:0,200',
  },
  {
    $formkit: 'text',
    name: 'description',
    label: 'Description',
  },
  {
    $formkit: 'text',
    name: 'price',
    label: 'Price',
    validation: 'required|number',
  },
  {
    $formkit: 'checkbox',
    name: 'in_stock',
    label: 'In stock',
  },
  {
    $formkit: 'select',
    name: 'category',
    label: 'Category',
    options: '$categoryOptions',
  },
  {
    $formkit: 'select',
    name: 'supplier',
    label: 'Supplier',
    options: '$supplierOptions',
    placeholder: 'Select a supplier…',
    validation: 'required',
  },
]

export const SupplierFormKitSchema = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'required|length:0,200',
  },
  {
    $formkit: 'email',
    name: 'email',
    label: 'Email',
    validation: 'email|length:0,254',
  },
]

export const CategoryWritableFormKitSchema = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'required|length:0,100',
  },
  {
    $formkit: 'text',
    name: 'slug',
    label: 'Slug',
    validation: 'required|length:0,100',
  },
]

export const OrderWritableFormKitSchema = [
  {
    $formkit: 'text',
    name: 'customer_name',
    label: 'Customer name',
    validation: 'required|length:0,200',
  },
  {
    $formkit: 'select',
    name: 'status',
    label: 'Status',
    options: [
      {
        value: 'pending',
        label: 'Pending',
      },
      {
        value: 'paid',
        label: 'Paid',
      },
      {
        value: 'shipped',
        label: 'Shipped',
      },
      {
        value: 'cancelled',
        label: 'Cancelled',
      },
    ],
  },
  {
    $formkit: 'list',
    name: 'items',
    children: [
      {
        $formkit: 'group',
        for: ['row', 'index', '$items_rows'],
        key: '$row.key',
        children: [
          {
            $formkit: 'select',
            name: 'product',
            label: 'Product',
            options: '$productOptions',
            placeholder: 'Select a product…',
            validation: 'required',
          },
          {
            $formkit: 'number',
            name: 'quantity',
            label: 'Quantity',
            validation: 'min:0|max:2147483647',
          },
          {
            $formkit: 'text',
            name: 'unit_price',
            label: 'Unit price',
            validation: 'required|number',
          },
          {
            $el: 'button',
            attrs: {
              type: 'button',
              class: 'formkit-remove',
              onClick: '$items_remove($index)',
            },
            children: 'Remove',
          },
        ],
      },
    ],
  },
]

export const OrderItemWritableFormKitSchema = [
  {
    $formkit: 'select',
    name: 'product',
    label: 'Product',
    options: '$productOptions',
    placeholder: 'Select a product…',
    validation: 'required',
  },
  {
    $formkit: 'number',
    name: 'quantity',
    label: 'Quantity',
    validation: 'min:0|max:2147483647',
  },
  {
    $formkit: 'text',
    name: 'unit_price',
    label: 'Unit price',
    validation: 'required|number',
  },
]

export const PatchedCategoryWritableFormKitSchema = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'length:0,100',
  },
  {
    $formkit: 'text',
    name: 'slug',
    label: 'Slug',
    validation: 'length:0,100',
  },
]

export const PatchedOrderWritableFormKitSchema = [
  {
    $formkit: 'text',
    name: 'customer_name',
    label: 'Customer name',
    validation: 'length:0,200',
  },
  {
    $formkit: 'select',
    name: 'status',
    label: 'Status',
    options: [
      {
        value: 'pending',
        label: 'Pending',
      },
      {
        value: 'paid',
        label: 'Paid',
      },
      {
        value: 'shipped',
        label: 'Shipped',
      },
      {
        value: 'cancelled',
        label: 'Cancelled',
      },
    ],
  },
  {
    $formkit: 'list',
    name: 'items',
    children: [
      {
        $formkit: 'group',
        for: ['row', 'index', '$items_rows'],
        key: '$row.key',
        children: [
          {
            $formkit: 'select',
            name: 'product',
            label: 'Product',
            options: '$productOptions',
            placeholder: 'Select a product…',
            validation: 'required',
          },
          {
            $formkit: 'number',
            name: 'quantity',
            label: 'Quantity',
            validation: 'min:0|max:2147483647',
          },
          {
            $formkit: 'text',
            name: 'unit_price',
            label: 'Unit price',
            validation: 'required|number',
          },
          {
            $el: 'button',
            attrs: {
              type: 'button',
              class: 'formkit-remove',
              onClick: '$items_remove($index)',
            },
            children: 'Remove',
          },
        ],
      },
    ],
  },
]

export const PatchedProductWritableFormKitSchema = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'length:0,200',
  },
  {
    $formkit: 'text',
    name: 'description',
    label: 'Description',
  },
  {
    $formkit: 'text',
    name: 'price',
    label: 'Price',
    validation: 'number',
  },
  {
    $formkit: 'checkbox',
    name: 'in_stock',
    label: 'In stock',
  },
  {
    $formkit: 'select',
    name: 'category',
    label: 'Category',
    options: '$categoryOptions',
  },
  {
    $formkit: 'select',
    name: 'supplier',
    label: 'Supplier',
    options: '$supplierOptions',
  },
]

export const PatchedSupplierWritableFormKitSchema = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'length:0,200',
  },
  {
    $formkit: 'email',
    name: 'email',
    label: 'Email',
    validation: 'email|length:0,254',
  },
]

export const ProductWritableFormKitSchema = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'required|length:0,200',
  },
  {
    $formkit: 'text',
    name: 'description',
    label: 'Description',
  },
  {
    $formkit: 'text',
    name: 'price',
    label: 'Price',
    validation: 'required|number',
  },
  {
    $formkit: 'checkbox',
    name: 'in_stock',
    label: 'In stock',
  },
  {
    $formkit: 'select',
    name: 'category',
    label: 'Category',
    options: '$categoryOptions',
  },
  {
    $formkit: 'select',
    name: 'supplier',
    label: 'Supplier',
    options: '$supplierOptions',
    placeholder: 'Select a supplier…',
    validation: 'required',
  },
]

export const SupplierWritableFormKitSchema = [
  {
    $formkit: 'text',
    name: 'name',
    label: 'Name',
    validation: 'required|length:0,200',
  },
  {
    $formkit: 'email',
    name: 'email',
    label: 'Email',
    validation: 'email|length:0,254',
  },
]
