// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client'
import { client } from './client.gen'
import type {
  CategoriesCreateData,
  CategoriesCreateResponses,
  CategoriesDestroyData,
  CategoriesDestroyResponses,
  CategoriesListData,
  CategoriesListResponses,
  CategoriesPartialUpdateData,
  CategoriesPartialUpdateResponses,
  CategoriesRetrieveData,
  CategoriesRetrieveResponses,
  CategoriesUpdateData,
  CategoriesUpdateResponses,
  OrdersCreateData,
  OrdersCreateResponses,
  OrdersDestroyData,
  OrdersDestroyResponses,
  OrdersListData,
  OrdersListResponses,
  OrdersPartialUpdateData,
  OrdersPartialUpdateResponses,
  OrdersRetrieveData,
  OrdersRetrieveResponses,
  OrdersUpdateData,
  OrdersUpdateResponses,
  ProductsCreateData,
  ProductsCreateResponses,
  ProductsDestroyData,
  ProductsDestroyResponses,
  ProductsListData,
  ProductsListResponses,
  ProductsPartialUpdateData,
  ProductsPartialUpdateResponses,
  ProductsRetrieveData,
  ProductsRetrieveResponses,
  ProductsUpdateData,
  ProductsUpdateResponses,
  SuppliersCreateData,
  SuppliersCreateResponses,
  SuppliersDestroyData,
  SuppliersDestroyResponses,
  SuppliersListData,
  SuppliersListResponses,
  SuppliersPartialUpdateData,
  SuppliersPartialUpdateResponses,
  SuppliersRetrieveData,
  SuppliersRetrieveResponses,
  SuppliersUpdateData,
  SuppliersUpdateResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * CRUD endpoints for product categories.
 */
export const categoriesList = <ThrowOnError extends boolean = false>(
  options?: Options<CategoriesListData, ThrowOnError>,
): RequestResult<CategoriesListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<CategoriesListResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/categories/',
    ...options,
  })

/**
 * CRUD endpoints for product categories.
 */
export const categoriesCreate = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesCreateData, ThrowOnError>,
): RequestResult<CategoriesCreateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<CategoriesCreateResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/categories/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * CRUD endpoints for product categories.
 */
export const categoriesDestroy = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesDestroyData, ThrowOnError>,
): RequestResult<CategoriesDestroyResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<CategoriesDestroyResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/categories/{id}/',
    ...options,
  })

/**
 * CRUD endpoints for product categories.
 */
export const categoriesRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesRetrieveData, ThrowOnError>,
): RequestResult<CategoriesRetrieveResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<CategoriesRetrieveResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/categories/{id}/',
    ...options,
  })

/**
 * CRUD endpoints for product categories.
 */
export const categoriesPartialUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesPartialUpdateData, ThrowOnError>,
): RequestResult<CategoriesPartialUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<CategoriesPartialUpdateResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/categories/{id}/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * CRUD endpoints for product categories.
 */
export const categoriesUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesUpdateData, ThrowOnError>,
): RequestResult<CategoriesUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).put<CategoriesUpdateResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/categories/{id}/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * CRUD endpoints for orders, including their line items.
 */
export const ordersList = <ThrowOnError extends boolean = false>(
  options?: Options<OrdersListData, ThrowOnError>,
): RequestResult<OrdersListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<OrdersListResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/orders/',
    ...options,
  })

/**
 * CRUD endpoints for orders, including their line items.
 */
export const ordersCreate = <ThrowOnError extends boolean = false>(
  options: Options<OrdersCreateData, ThrowOnError>,
): RequestResult<OrdersCreateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<OrdersCreateResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/orders/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * CRUD endpoints for orders, including their line items.
 */
export const ordersDestroy = <ThrowOnError extends boolean = false>(
  options: Options<OrdersDestroyData, ThrowOnError>,
): RequestResult<OrdersDestroyResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<OrdersDestroyResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/orders/{id}/',
    ...options,
  })

/**
 * CRUD endpoints for orders, including their line items.
 */
export const ordersRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<OrdersRetrieveData, ThrowOnError>,
): RequestResult<OrdersRetrieveResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<OrdersRetrieveResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/orders/{id}/',
    ...options,
  })

/**
 * CRUD endpoints for orders, including their line items.
 */
export const ordersPartialUpdate = <ThrowOnError extends boolean = false>(
  options: Options<OrdersPartialUpdateData, ThrowOnError>,
): RequestResult<OrdersPartialUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<OrdersPartialUpdateResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/orders/{id}/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * CRUD endpoints for orders, including their line items.
 */
export const ordersUpdate = <ThrowOnError extends boolean = false>(
  options: Options<OrdersUpdateData, ThrowOnError>,
): RequestResult<OrdersUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).put<OrdersUpdateResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/orders/{id}/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * CRUD endpoints for products.
 */
export const productsList = <ThrowOnError extends boolean = false>(
  options?: Options<ProductsListData, ThrowOnError>,
): RequestResult<ProductsListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ProductsListResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/products/',
    ...options,
  })

/**
 * CRUD endpoints for products.
 */
export const productsCreate = <ThrowOnError extends boolean = false>(
  options: Options<ProductsCreateData, ThrowOnError>,
): RequestResult<ProductsCreateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<ProductsCreateResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/products/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * CRUD endpoints for products.
 */
export const productsDestroy = <ThrowOnError extends boolean = false>(
  options: Options<ProductsDestroyData, ThrowOnError>,
): RequestResult<ProductsDestroyResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<ProductsDestroyResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/products/{id}/',
    ...options,
  })

/**
 * CRUD endpoints for products.
 */
export const productsRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<ProductsRetrieveData, ThrowOnError>,
): RequestResult<ProductsRetrieveResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<ProductsRetrieveResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/products/{id}/',
    ...options,
  })

/**
 * CRUD endpoints for products.
 */
export const productsPartialUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ProductsPartialUpdateData, ThrowOnError>,
): RequestResult<ProductsPartialUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<ProductsPartialUpdateResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/products/{id}/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * CRUD endpoints for products.
 */
export const productsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ProductsUpdateData, ThrowOnError>,
): RequestResult<ProductsUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).put<ProductsUpdateResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/products/{id}/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * CRUD endpoints for suppliers.
 */
export const suppliersList = <ThrowOnError extends boolean = false>(
  options?: Options<SuppliersListData, ThrowOnError>,
): RequestResult<SuppliersListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<SuppliersListResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/suppliers/',
    ...options,
  })

/**
 * CRUD endpoints for suppliers.
 */
export const suppliersCreate = <ThrowOnError extends boolean = false>(
  options: Options<SuppliersCreateData, ThrowOnError>,
): RequestResult<SuppliersCreateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<SuppliersCreateResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/suppliers/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * CRUD endpoints for suppliers.
 */
export const suppliersDestroy = <ThrowOnError extends boolean = false>(
  options: Options<SuppliersDestroyData, ThrowOnError>,
): RequestResult<SuppliersDestroyResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<SuppliersDestroyResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/suppliers/{id}/',
    ...options,
  })

/**
 * CRUD endpoints for suppliers.
 */
export const suppliersRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<SuppliersRetrieveData, ThrowOnError>,
): RequestResult<SuppliersRetrieveResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<SuppliersRetrieveResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/suppliers/{id}/',
    ...options,
  })

/**
 * CRUD endpoints for suppliers.
 */
export const suppliersPartialUpdate = <ThrowOnError extends boolean = false>(
  options: Options<SuppliersPartialUpdateData, ThrowOnError>,
): RequestResult<SuppliersPartialUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<SuppliersPartialUpdateResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/suppliers/{id}/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * CRUD endpoints for suppliers.
 */
export const suppliersUpdate = <ThrowOnError extends boolean = false>(
  options: Options<SuppliersUpdateData, ThrowOnError>,
): RequestResult<SuppliersUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).put<SuppliersUpdateResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'sessionid',
        type: 'apiKey',
      },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/api/suppliers/{id}/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
